# Generated by Django 4.0.1 on 2022-02-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
