# Generated by Django 4.0.1 on 2022-02-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_name_posts_heading_posts_post_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
