# Generated by Django 4.0.1 on 2022-02-23 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_remove_posts_user_posts_student_posts_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='student',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='teacher',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
