# Generated by Django 4.0.1 on 2022-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_posts_student_remove_posts_teacher_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_by',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_email',
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/img'),
        ),
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
