# Generated by Django 4.0.1 on 2022-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_posts_content_remove_posts_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='text',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
