# Generated by Django 4.0.1 on 2022-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
