# Generated by Django 4.0.1 on 2022-02-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_otp'),
        ('teachers', '0012_alter_teacher_otp'),
        ('posts', '0013_posts_post_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='posts',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
