# Generated by Django 4.0.1 on 2022-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
