# Generated by Django 4.0.1 on 2022-02-26 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_remove_postlikes_likes_alter_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_on_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
