# Generated by Django 4.0.1 on 2022-02-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentclassinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
    ]
