# Generated by Django 4.0.1 on 2022-02-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentclassinfo_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studentClassInfo', to='students.student'),
        ),
    ]
