# Generated by Django 4.0.1 on 2022-02-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
