# Generated by Django 4.0.1 on 2022-02-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='Description',
            new_name='details',
        ),
    ]
