# Generated by Django 4.0.1 on 2022-02-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Christian', 'Christan')], max_length=20)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, max_length=70, null=True)),
                ('blood_group', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='Bangladesh', max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='teachers/dp/')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=50)),
                ('exp_start_date', models.DateField()),
                ('exp_end_date', models.DateField()),
                ('exp_designation', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TeacherExperience', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_edu', models.CharField(choices=[('Bsc', 'Bsc'), ('Msc', 'Msc'), ('Phd', 'Phd')], max_length=5)),
                ('speciality', models.CharField(max_length=20)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TeacherEducation', to='teachers.teacher')),
            ],
        ),
    ]
