# Generated by Django 4.0.1 on 2022-02-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='archived_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='modified_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
