# Generated by Django 4.0.1 on 2022-02-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherEducation', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherexperience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherExperience', to='teachers.teacher'),
        ),
    ]
