# Generated by Django 4.0.1 on 2022-02-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teachereducation_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
