# Generated by Django 4.0.1 on 2022-02-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
