# Generated by Django 4.0.1 on 2022-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(max_length=255, null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(max_length=255, null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(max_length=255, null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('addr_street', models.CharField(max_length=75)),
                ('addr_city', models.CharField(max_length=20)),
                ('addr_zip', models.PositiveIntegerField()),
                ('addr_country', models.CharField(max_length=20)),
                ('follow_phone', models.CharField(max_length=20, unique=True)),
                ('follow_email', models.EmailField(max_length=254, unique=True)),
                ('follow_facebook', models.URLField()),
                ('follow_linkedin', models.URLField()),
                ('follow_instagram', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
