# Generated by Django 4.0.1 on 2022-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
